var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":58,"id":6924,"methods":[{"el":36,"sc":2,"sl":34},{"el":39,"sc":2,"sl":37},{"el":42,"sc":2,"sl":40},{"el":45,"sc":2,"sl":43},{"el":48,"sc":2,"sl":46},{"el":51,"sc":2,"sl":49},{"el":54,"sc":2,"sl":52},{"el":57,"sc":2,"sl":55}],"name":"AuthorizationToken","sl":24}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_102":{"methods":[{"sl":52}],"name":"testGetNotification","pass":true,"statements":[{"sl":53}]},"test_110":{"methods":[{"sl":52}],"name":"testGetUserLazy","pass":true,"statements":[{"sl":53}]},"test_125":{"methods":[{"sl":52}],"name":"testGetProfile","pass":true,"statements":[{"sl":53}]},"test_130":{"methods":[{"sl":52}],"name":"testGetUsersLazy","pass":true,"statements":[{"sl":53}]},"test_30":{"methods":[{"sl":52}],"name":"testGetSupersedePlatforms","pass":true,"statements":[{"sl":53}]},"test_43":{"methods":[{"sl":37},{"sl":40},{"sl":43},{"sl":49},{"sl":52},{"sl":55}],"name":"testPublishAdaptionAlertMessage","pass":true,"statements":[{"sl":38},{"sl":41},{"sl":44},{"sl":50},{"sl":53},{"sl":56}]},"test_44":{"methods":[{"sl":52}],"name":"testCreateGetDeleteSupersedePlatform","pass":true,"statements":[{"sl":53}]},"test_52":{"methods":[{"sl":52}],"name":"setupSupersedePlatforms","pass":true,"statements":[{"sl":53}]},"test_7":{"methods":[{"sl":52}],"name":"testGetUsers","pass":true,"statements":[{"sl":53}]},"test_84":{"methods":[{"sl":52}],"name":"testGetNotifications","pass":true,"statements":[{"sl":53}]},"test_94":{"methods":[{"sl":52}],"name":"testGetProfiles","pass":true,"statements":[{"sl":53}]},"test_96":{"methods":[{"sl":52}],"name":"testGetUser","pass":true,"statements":[{"sl":53}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [43], [43], [], [43], [43], [], [43], [43], [], [], [], [], [43], [43], [], [7, 102, 84, 43, 44, 94, 125, 96, 52, 130, 30, 110], [7, 102, 84, 43, 44, 94, 125, 96, 52, 130, 30, 110], [], [43], [43], [], []]
