var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":61,"id":3500,"methods":[{"el":60,"sc":5,"sl":47}],"name":"ReplanFeatureReleaseJsonDeserializer","sl":38}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":47}],"name":"testGetFeaturesOfProjectById","pass":true,"statements":[{"sl":51},{"sl":53},{"sl":54}]},"test_16":{"methods":[{"sl":47}],"name":"testDeleteDependenciesOfFeatureByIdOfProjectById","pass":true,"statements":[{"sl":51},{"sl":53},{"sl":54}]},"test_20":{"methods":[{"sl":47}],"name":"testAddDeleteSkillsOfFeatureByIdOfProjectById","pass":true,"statements":[{"sl":51},{"sl":53},{"sl":54}]},"test_41":{"methods":[{"sl":47}],"name":"testGetFeatureByIdOfProjectById","pass":true,"statements":[{"sl":51},{"sl":53},{"sl":54}]},"test_5":{"methods":[{"sl":47}],"name":"testAddDeleteDependenciesOfFeatureByIdOfProjectById","pass":true,"statements":[{"sl":51},{"sl":53},{"sl":54}]},"test_51":{"methods":[{"sl":47}],"name":"testAddDeleteFeaturesOfReleaseByIdOfProjectById","pass":true,"statements":[{"sl":51},{"sl":53},{"sl":54}]},"test_65":{"methods":[{"sl":47}],"name":"testDeleteSkillsOfFeatureByIdOfProjectById","pass":true,"statements":[{"sl":51},{"sl":53},{"sl":54}]},"test_77":{"methods":[{"sl":47}],"name":"testDeleteFeaturesOfReleaseByIdOfProjectById","pass":true,"statements":[{"sl":51},{"sl":53},{"sl":54},{"sl":56},{"sl":57},{"sl":59}]},"test_83":{"methods":[{"sl":47}],"name":"testCreateAndDeleteFeatureForProject","pass":true,"statements":[{"sl":51},{"sl":53},{"sl":54}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [77, 5, 51, 65, 41, 20, 1, 83, 16], [], [], [], [77, 5, 51, 65, 41, 20, 1, 83, 16], [], [77, 5, 51, 65, 41, 20, 1, 83, 16], [77, 5, 51, 65, 41, 20, 1, 83, 16], [], [77], [77], [], [77], [], []]
